### ISSUE TITLE
Djongo migration error

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [L04DB4L4NC3R/medicine-delivery#1]
## What I did
```
python manage.py migrate
```

## Output

```bash
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1385, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/collection.py", line 852, in _update
    retryable_write=retryable_write)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/collection.py", line 822, in _update
    retryable_write=retryable_write).copy()
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Transaction numbers are only allowed on storage engines that support document-level locking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 819, in parse
    return handler(self, statement)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 917, in _create
    upsert=True
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/collection.py", line 1003, in update_one
    session=session),
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/collection.py", line 856, in _update_retryable
    _update, session)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1492, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1426, in _retry_with_session
    raise OperationFailure(errmsg, exc.code, exc.details)
pymongo.errors.OperationFailure: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 298, in create_model
    self.execute(sql, params or None)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 754, in __init__
    self.parse()
  File "/home/angad/Desktop/STUFF/xwxp/medicine-delivery/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 832, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "django_content_type" ("id" int32 NOT NULL PRIMARY KEY AUTOINCREMENT, "name" string NOT NULL, "app_label" string NOT NULL, "model" string NOT NULL)
Params: None
Pymongo error: {'operationTime': Timestamp(1568714868, 2), 'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on storage engines that support document-level locking', 'code': 20, 'codeName': 'IllegalOperation', '$clusterTime': {'clusterTime': Timestamp(1568714868, 2), 'signature': {'hash': b'S;\xc9\xd7\x96\xf3\x85\xb4\xd7Z\xa4\xc3\xfe(\xea\xb3\xf7\xc7\xae\xea', 'keyId': 6711256982663200769}}}
Version: 1.2.36

```

**Comment by L04DB4L4NC3R** [comment]
Using postgres
